### ISSUE TITLE
java.lang.NoClassDefFoundError: javafx/application/Application on Ubuntu 20.04.4

### ISSUE THREAD

**Issue by jrd10** [jgneff/openjfx#2]
Hi John and all the team, thank you for Openjfx

I use a Java application and I have this error message:
"Impossible to find or to load the main class..."...  

```
Erreur : impossible de trouver ou de charger la classe principale rg.espfx.EspFx
Causé par : java.lang.NoClassDefFoundError: javafx/application/Application
```
_Below the complete error message._

Please, note that the editor recommand to use the Oracle environment.

Thank you for your feedback and confirm if, in this case, it is better to use the Oracle environment.
Please note, I am not an expert with Java :).

The application: https://thopt.s4e2.com/jml/en/thermoptim-en/download

My environment is:

I am on Ubuntu 20.04.4, and I have installed openjfx with Snap.

```
 jrd_10@my-pc:~/...$ snap info openjfx
name:      openjfx
summary:   Current JavaFX release and early-access builds
publisher: John Neffenger (jgneff)
store-url: https://snapcraft.io/openjfx
contact:   https://github.com/jgneff/openjfx/discussions
license:   GPL-2.0-with-classpath-exception
description: |
  OpenJFX is the official open-source project that develops JavaFX,
  a cross-platform application framework for developing and deploying
  rich client applications that operate consistently across a diverse
  set of platforms.
  
  This package, together with OpenJDK 11 or later, provides everything
  you need to develop a JavaFX application on Linux, including all
  of the latest JAR files, native libraries, JMOD archives, API
  documentation, and source code of JavaFX.
  
  To get started, see the README file for this package on GitHub:
  
  https://github.com/jgneff/openjfx
  
  Java and OpenJDK are trademarks or registered trademarks of Oracle
  and/or its affiliates.
commands:
  - openjfx
snap-id:      FpIMJxPmRiPFwL2hGqujo314Hkiwu5XY
tracking:     latest/edge
refresh-date: yesterday at 19:29 CEST
channels:
  latest/stable:    19+11 2022-09-25 (536) 103MB -
  latest/candidate: ↑                            
  latest/beta:      ↑                            
  latest/edge:      20+3  2022-09-25 (535) 103MB -
installed:          20+3             (535) 103MB -

```

Java version:
```
jrd_10@my-pc:~/...$ java -version
openjdk version "11.0.16" 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

The complete error message is:

```
jrd_10@my-pc:~/...$ ./NavThopt
commande Java:  /usr/bin/java
Installed java version: 2022-07-19
Required JRE version: 1.4+..OK
AppRoot:  .
/home/jrd_10/Desktop/NavThopt_linux_282_Fr/NavThopt_linux
+ exec /usr/bin/java -cp lib/bibTEP.jar:lib/gef2.jar:lib/im2.jar:lib/inth2.jar:lib/imStruc2.jar:lib/ThoptDemo2.jar:lib/ThoptEdu2.jar:lib/Thopt2.jar:lib/EspFx.jar:extBib.zip:extUser2.zip:extThopt2.zip rg.espfx.EspFx
Erreur : impossible de trouver ou de charger la classe principale rg.espfx.EspFx
Causé par : java.lang.NoClassDefFoundError: javafx/application/Application
```

Thank you for your time.

**Comment by jgneff** [comment]
Your `java` command is missing the module path argument (`--module-path` or `-p`). You need to put the directory containing the JavaFX modular JAR files on the module path for the Java launcher to find them. Note that it's not enough to put the JavaFX SDK library directory on the class path

```console
$ java -cp "/snap/openjfx/current/sdk/lib/*" -jar dist/hello-javafx-1.0.0.jar 
Error: Could not find or load main class org.status6.hello.javafx.Hello
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

Invoking the Java application from its main class fails, too:

```console
$ java -cp "dist/hello-javafx-1.0.0.jar:/snap/openjfx/current/sdk/lib/*" org.status6.hello.javafx.Hello
Error: JavaFX runtime components are missing, and are required to run this application
```

See the notes in the documentation for the following:

* [Class Application](https://openjfx.io/javadoc/19/javafx.graphics/javafx/application/Application.html)
* [Module javafx.graphics](https://openjfx.io/javadoc/19/javafx.graphics/module-summary.html)
* [Method Platform.startup](https://openjfx.io/javadoc/19/javafx.graphics/javafx/application/Platform.html#startup(java.lang.Runnable))

which state:

> **Note:** The JavaFX classes must be loaded from a set of named `javafx.*` modules on the *module path*. Loading the JavaFX classes from the classpath is not supported. A warning is logged when the JavaFX runtime is started if the JavaFX classes are not loaded from the expected named module. This warning is logged regardless of whether the JavaFX runtime was started by calling this method or automatically as described above.

Also see the **Important Changes** section at the top of the [Release Notes for JavaFX 16](https://github.com/openjdk/jfx/blob/master/doc-files/release-notes-16.md).

Start your application with the JavaFX SDK library on the module path as in the example below, and it should work. This example starts the application as the main class in a JAR file:

```console
$ java -p /snap/openjfx/current/sdk/lib --add-modules javafx.controls -jar dist/hello-javafx-1.0.0.jar 
Hello World!
```

You don't need to make your application modular, but if you do, you can also start it as the main class in a module:

```console
$ java -p dist/hello-javafx-1.0.0.jar:/snap/openjfx/current/sdk/lib -m org.status6.hello.javafx
Hello World!
```

**Comment by jrd10** [comment]
Hello, thank you for your fast feedback.
I am not an expert in Java.

What I can say is, if I run `openjfx`, terminal returns `/var/snap/openjfx/535/openjfx.env`

As file to run the app there is no .jar file, only .sh file or without extension.

In the directory where the app is, I tried something like 
`java -p /snap/openjfx/current/sdk/lib --add-modules javafx.controls ./NavThoptLinuxD` 

I've got this error message...
```
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: /snap/openjfx/current/sdk/lib/javafx.base.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 61.0
```
The editor recommend to use Oracle environment, not the openJDK.
Due to my lack of knowledge in Java, I am going to change my environment.

Thank you for your time and interest.

**Comment by jgneff** [comment]
Sorry, I just realized you are not a JavaFX software developer. I assumed you were the author of the Thermoptim browser application, but you clearly state in your first comment that you're just trying to use it. I'm sorry for the misunderstanding.

In this case, you should do [exactly what's recommended](https://thopt.s4e2.com/jml/en/thermoptim-en/download?view=article&id=35:installing-the-oracle-jre-on-ubuntu&catid=2:uncategorised) on the Thermoptim download page for "Installing the Oracle JRE on Ubuntu." The link to the Oracle Java 8 runtime that they recommend has built-in support for JavaFX. Just follow their installation instructions, and it should work fine. The current Java 8 download file for 64-bit Linux is `jre-8u341-linux-x64.tar.gz`.

The OpenJFX Snap package is a Software Development Kit intended to be used only by Java software developers writing JavaFX applications.

**Comment by jrd10** [comment]
Hi @jgneff thank you for your time and sorry if I have not been clear.
Yes, I will do that.

At the same time, I have a question for a Java expert :).

Could we install Java on Ubuntu **Server** environment and make Java application running?
Or do we need necessarily a desktop environment 

Thank you for your feedback.

Take care. José

**Comment by jrd10** [comment]
Thank you for this quick and complete answer.

I will try, give me the time to do that :). I will provide you feedback.

Many thanks for your time and interest, José

**Comment by jgneff** [comment]
Please start a [discussion](https://github.com/jgneff/openjfx/discussions) if you encounter any other problems.

**Comment by MaxBarraclough** [comment]
As a follow-on to this issue:

Similar to jrd10, I had to figure out how to use the snap, and didn't get much benefit from the documentation currently on the homepage.

I suggest adding a complete example command-line invocation under the _Usage_ section, like the example above:
`java -p /snap/openjfx/current/sdk/lib --add-modules javafx.controls -jar dist/hello-javafx-1.0.0.jar`
or better still, using the more instructional long-form flag:
`java --module-path /snap/openjfx/current/sdk/lib --add-modules javafx.controls -jar dist/hello-javafx-1.0.0.jar`


Thanks for creating the snap package.
